[build]
  command = "cd shadcn-ui && npm install && npm run build"
  publish = "shadcn-ui/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
node_version = { version = "16.14.0" }
